### ISSUE TITLE
ShinyWidgets airDatepicker not working

### ISSUE THREAD

**Issue by FredericKruger** [RinteRface/bs4Dash#98]
Hi
when using the Widget airDatepickerInput or airMonthpickerInput from ShinyWidgets, I do not get the same behaviour as if I used shinydashboard.
The app will not load if put in the sidebar.
I planed to move from shinydashboard to bs4Dash, but the use of airMonthpickerInput is critical.
Would there be an alternative ?

Fred

**Comment by india-babai** [comment]
Hello,
I'm facing the same issue with airDatepickerInput as in the picture; 
![test](https://user-images.githubusercontent.com/35023204/76657371-b20ec180-6597-11ea-9e94-37955f48ccf0.PNG)

It's not looking line and if I put the timepicker option, its not even showing up.

Arijit

**Comment by DivadNojnarg** [comment]
Could you send me a reproducible example please?

**Comment by india-babai** [comment]
```
ui <- bs4Dash::bs4DashPage(
  body = bs4DashBody(
    shinyWidgets::airDatepickerInput("airdate", "Date", timepicker = T)
  )
)

server <- function(input, output){
  
}

shinyApp(ui, server)
```

The above code is producing the aforementioned distorted airDatepicker.

**Comment by india-babai** [comment]
```
ui <- fluidPage(
  shinyWidgets::airDatepickerInput("airdate", "Date", timepicker = T)
)

shinyApp(ui, server)
```
![image](https://user-images.githubusercontent.com/35023204/76687978-c5c92f00-664e-11ea-8d8c-87ec63cb5615.png)


It's working nicely in fluidPage.

**Comment by FredericKruger** [comment]
Thanks for those examples india-babai. This describes the behavior well.

**Comment by artemklevtsov** [comment]
it work correct if used in the `renderUI`.

**Comment by DivadNojnarg** [comment]
Sorry if I cannot help at the moment. Due to the current circumstances, I have very limited work time and no time for open source. Thanks for your understanding!

**Comment by pvictor** [comment]
Hello,
There is a javascript conflict between AirDatepicker and JQuery UI's Datepicker. If you install development version of shinyWidgets, it should be fixed.

```r
devtools::install_github("dreamRs/shinyWidgets")
```

**Comment by DivadNojnarg** [comment]
@pvictor : thanks! Let me know when shinyWidgets gets updated on CRAN. I will add a minimum version number to bs4Dash

**Comment by artemklevtsov** [comment]
Still not works in control bar. Pop up calendar not appears.

```r
library(shiny)
library(bs4Dash)
library(shinyWidgets)

ui <- bs4Dash::bs4DashPage(
  navbar = bs4DashNavbar(),
  body = bs4DashBody(),
  controlbar = bs4DashControlbar(
    airDatepickerInput("airdate", "Date", timepicker = T)
  )
)
server <- function(input, output){}
shinyApp(ui, server)
```

**Comment by pvictor** [comment]
That's a z index issue, the Air datepicker is behind the controlbar, you can do :

```r
bs4DashControlbar(
  width = 280,
  tags$style(".airdatepicker {z-index: 1500;}"),
  airDatepickerInput("airdate", "Date", timepicker = T),
  
  # or display inline
  airDatepickerInput("airdateI", "Date", timepicker = T, inline = TRUE)
)
```

Victor

**Comment by artemklevtsov** [comment]
@pvictor thank for the workaround. I hope this will be fixed in the future release.

**Comment by DivadNojnarg** [comment]
Fixed in latest development version
